=== akyekth/Webservices/XMLProj/build/classes/schemas/ApplicantProfile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3schools.com/myns/" targetNamespace="http://www.w3schools.com/myns/" elementFormDefault="qualified">
	<xs:include schemaLocation="CompanyInfo.xsd"/>
	<xs:include schemaLocation="EmploymentRecord.xsd"/>
	<xs:include schemaLocation="ShortCV.xsd"/>
	<xs:include schemaLocation="Transcripts.xsd"/>
	<xs:element name="applicantProfile">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="userdata">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="fullname" type="xs:string"/>
							<xs:element name="personnummer" type="xs:string"/>
							<xs:element name="personalLetter" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="employmentRecord">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="employment">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="code" type="xs:string"/>
										<xs:element name="from" type="xs:date"/>
										<xs:element name="to" type="xs:date"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="degrees">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="degree">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="uniName" type="xs:string"/>
										<xs:element name="type" type="xs:string"/>
										<xs:element name="GPA" type="xs:float"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== akyekth/Webservices/XMLProj/resources/xml/ApplicantProfileT.xml
<?xml version="1.0" encoding="UTF-8"?>
<applicantProfile xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                   xmlns='http://www.w3schools.com/myns/'
                   xsi:schemaLocation='http://www.w3schools.com/myns/ file://schemas/ApplicantProfile.xsd'>

    <userdata>
        <fullname>Johan Johansson</fullname>
        <personnummer>880513-1234</personnummer>
        <personalLetter>I am the best in the world</personalLetter>
    </userdata>

    <employmentRecord>
        <employment>
            <code>5000</code>
            <from>2014-09-19</from>
            <to>2015-09-19</to>
        </employment>
        <employment>
            <code>5001</code>
            <from>2015-09-20</from>
            <to>2016-09-19</to>
        </employment>
        <employment>
            <code>5002</code>
            <from>2016-09-20</from>
            <to>2017-09-19</to>
        </employment>
    </employmentRecord>

    <degrees>
        <degree>
            <uniName>KTH</uniName>
            <type>Bachelor</type>
            <GPA>3.5</GPA>
        </degree>
    </degrees>
</applicantProfile>
