=== akyekth/Webservices/XMLProj/build/classes/schemas/CompanyInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3schools.com/myns/" targetNamespace="http://www.w3schools.com/myns/" elementFormDefault="qualified">
	<xs:element name="companyInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="company" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="2"/>
										<xs:maxLength value="15"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="code">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="\d{4}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="phone">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="\d{2}-\d{8}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== akyekth/Webservices/XMLProj/resources/xml/CompanyInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<companyInfo xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
             xmlns='http://www.w3schools.com/myns/'
             xsi:schemaLocation='http://www.w3schools.com/myns/ file://schemas/CompanyInfo.xsd'>

    <company>
        <name>Google</name>
        <code>5000</code>
        <phone>08-55556000</phone>
    </company>
    <company>
        <name>Spotify</name>
        <code>5001</code>
        <phone>08-55556001</phone>
    </company>
    <company>
        <name>Ericsson</name>
        <code>5002</code>
        <phone>08-55556002</phone>
    </company>

</companyInfo>
