=== akyekth/Webservices/XMLProj/build/classes/schemas/EmploymentRecord.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3schools.com/myns/" targetNamespace="http://www.w3schools.com/myns/" elementFormDefault="qualified">
	<xs:element name="employmentRecord">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="personnummer">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="\d{6}-\d{4}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="employment" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="code">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="\d{4}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="from">
								<xs:simpleType>
									<xs:restriction base="xs:date">
										<xs:pattern value="\d{2}-\d{2}-\d{4}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="to">
								<xs:simpleType>
									<xs:restriction base="xs:date">
										<xs:pattern value="\d{2}-\d{2}-\d{4}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== akyekth/Webservices/XMLProj/resources/xml/EmploymentRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<employmentRecord xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                   xmlns='http://www.w3schools.com/myns/'
                   xsi:schemaLocation='http://www.w3schools.com/myns/ file://schemas/EmploymentRecord.xsd'>
    <personnummer>880513-1234</personnummer>
    <employment>
        <code>5000</code>
        <from>2014-09-19</from>
        <to>2015-09-19</to>
    </employment>
    <employment>
        <code>5001</code>
        <from>2015-09-20</from>
        <to>2016-09-19</to>
    </employment>
    <employment>
        <code>5002</code>
        <from>2016-09-20</from>
        <to>2017-09-19</to>
    </employment>
</employmentRecord>
