=== akyekth/Webservices/XMLProj/resources/schemas/Transcripts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3schools.com/myns/" targetNamespace="http://www.w3schools.com/myns/" elementFormDefault="qualified">
	<xs:element name="transcript">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="degrees" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="degree">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="uniName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="2"/>
													<xs:maxLength value="9"/>
													<xs:pattern value="([A-Z])*"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="type" type="xs:string"/>
										<xs:element name="GPA">
											<xs:simpleType>
												<xs:restriction base="xs:float">
													<!--<xs:fractionDigits value="2"/>-->
													<xs:minExclusive value="0"/>
													<xs:pattern value="\d+\.\d"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="courses" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="course">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="courseName" type="xs:string"/>
										<xs:element name="creditHours" type="xs:float"/>
										<xs:element name="grade">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="1"/>
													<xs:enumeration value="A"/>
													<xs:enumeration value="B"/>
													<xs:enumeration value="C"/>
													<xs:enumeration value="D"/>
													<!--<xs:pattern value="[ABCD]"/> -->
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="score" type="xs:float"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== akyekth/Webservices/XMLProj/build/classes/xml/Transcripts.xml
<?xml version="1.0" encoding="UTF-8"?>
<transcript xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                   xmlns='http://www.w3schools.com/myns/'
                   xsi:schemaLocation='http://www.w3schools.com/myns/ file://schemas/Transcripts.xsd'>

    <degrees>
        <degree>
            <uniName>KTH</uniName>
            <type>Bachelor</type>
            <GPA>0</GPA>
        </degree>
    </degrees>

    <courses>
        <course>
            <courseName>Introduction to Algorithms</courseName>
            <crediHours>3</crediHours>
            <grade>A</grade>                
            <score>B</score>
        </course>
        <course>
            <courseName>Software Engineering</courseName>
            <crediHours>2</crediHours>
            <grade>B</grade>  
            <score>A</score>
        </course>
    </courses>

</transcript>
